# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  dockerpocfordotnet:
    image: dockerpocfordotnet
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5275:5275
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
